[package]
name = "copiosis-rocket"
version = "0.2.0"
authors = ["Michal Mauser <michal.mauser@zeitgeistmovement.cz>"]

[dependencies]
rocket = "0.4.0-rc.1"
rusqlite = "0.13"
serde = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
version = "0.4.0-rc.1"
default-features = false
features = ["handlebars_templates"]

